#!/usr/bin/with-contenv bash

echo "-----------------"
echo "Starting Codi-MD."
echo "-----------------"

#check for any additional environmental variables
ENV_VARIABLES=$(printenv | grep CMD | sed -e 's/$/ \\/')

RUN_CMD="${ENV_VARIABLES} CMD_CONFIG_FILE=/config/config.json
          CMD_DB_URL=${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/codimd \
          CMD_DOMAIN=${DOMAIN} \
          CMD_PROTOCOL_USESSL=true \
          node app.js"

cd /opt/codimd || exit

exec \
      s6-setuidgid abc /bin/bash -c "${RUN_CMD}"
      