#!/usr/bin/with-contenv bash

# copy config.json if doesn't exist
[[ ! -f /config/config.json]] && \
    cp /defaults/config.json /config/config.json

# make images folder
[[ ! -d /config/resources ]] && \
    mkdir -p /config/resources/{docs,uploads,views}

# check for addition CMD env variables
ENV_VARIABLES=$(printenv | grep CMD | sed -e 's/$/ \\/')

# permissions
chown -R abc:abc \
	/app \
    /config